### ISSUE TITLE
Only Created NFTs are Transferable

### ISSUE THREAD

**Issue by kespinola** [holaplex/hub-starter#18]
## Goal
The user can only allow to transfer NFTs that are created.

## Requirements
- Disable the transfer button on the wallets page while the NFT is still has a status of creating.
- Provide visual indicator to the user on the creation status of the NFT.

![Image](https://user-images.githubusercontent.com/2388118/250660546-a7fe6a19-df7a-4f79-8176-40e704f7e079.png)

**Comment by alchemistgo87** [comment]
https://github.com/holaplex/hub-starter/pull/19
