### ISSUE TITLE
Head to Head Starter

### ISSUE THREAD

**Issue by kespinola** [holaplex/hub-starter#23]
## Goal
Head to head voting using NFTs.

![Image](https://user-images.githubusercontent.com/2388118/254639044-225610c0-b370-43bf-95b3-e495a0cb40dd.png)

## Requirements
- User can only vote once
- User can not re-mint
- Display current "votes" (aka mint totals) after user place vote (aka mints NFT)
- Use can view their vote NFT on the collectables page
- Display text message "You choose [blockchain]" for displaying which the user picked (This should persist when the visit the page again)

**Comment by kespinola** [comment]
```grahql
type Vote {
  A,
  B
}

mutation PlaceVote(vote: $selection) {
  mint(vote: "A") {
}
}

```

async mint({ vote }) {
  const dropId =  process.env[`HOLAPLEX_{vote}_VOTE_DROP_ID`]

  holplex.mutation
}

```
collectible(id: $HOLAPLEX_A_VOTE_DROP_ID) {
  totalMints
  mintHistory {
  }
}
```
NEXT_PUBLIC_HOLAPLEX_A_VOTE_DROP_ID=
HOALPLEX_B_VOTE_DROP_ID=

## Notes
- Use the existence of an NFT in the users wallet to show their vote result. Check the blockchain of the nft's collection to display the "You choose {user.wallets.collection.blockchain}"

**Comment by alchemistgo87** [comment]
https://github.com/holaplex/hub-starter-vote/pull/1
