### ISSUE TITLE
Hub Starter Not Enough Credits

### ISSUE THREAD

**Issue by kespinola** [holaplex/hub-starter#8]
## Goal
The hub starter has example of handling no credit errors when users attempt to mint an NFT.

https://user-images.githubusercontent.com/24394839/237482523-7c2cb2a1-3588-465d-9477-e2e0b685b94a.mov

**Comment by kespinola** [comment]
@alchemistgo87 don't show specific error returned by the API but do display generic error toast of "Unable to mint please try again or reach out to support."

**Comment by alchemistgo87** [comment]
https://github.com/holaplex/hub-starter/pull/10
